apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 1
    name: go-ping-pong
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: go-ping-pong
    name: go-ping-pong
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: go-ping-pong:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/jewzaam/go-ping-pong
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        env:
        - name: GIT_SSL_NO_VERIFY
          value: "true"
        from:
          kind: DockerImage
          name: docker.io/golang:1.9
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - type: Generic
      generic:
        secret: "nmalik-hook"
kind: List
metadata: {}

